# see http://about.travis-ci.org/docs/user/languages/cpp/ for more hints
language: cpp

# list any compiler you want to test against
compiler:
  - clang
  - gcc

# list branches you want to run continuous integration on
branches:
  only:
    - develop

# create build directory
before_install:
  - mkdir -p build
  - cd src

# run Makefile
script: make